[package]
name = "sentiment_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
csv = "1.2.1"
ndarray = "0.15.6"
rand = "0.8.5"
rust-bert = "0.20.0"
tch = "0.10.0"
